server:
  port: 8083

logging:
  level:
    org.springframework:
      web.reactive: INFO #DEBUG for web reactive logging
      web.reactive.function.client.ExchangeFunctions: INFO #DEBUG for logging WebClient requests

basic-auth:
  #helloworld - encrypted using Bcrypt
  admin-password: "{bcrypt}$2a$10$/Djv1Ternoa7ipSYG1sRAOpcv3qWk/acVMCtJHNy9bON/PoaHNWFO"